"""Run the notification A/B test end to end.

Reads the experiment assignment table (parquet from the generator, or the
committed sample), runs a two-proportion z-test and a Welch t-test, computes the
required sample size and the achieved power, renders plots, and writes a
``results.md`` writeup next to this file.

Usage
-----
    python -m analysis.ab_test.ab_test                       # uses data/raw
    python -m analysis.ab_test.ab_test --source data/raw/sample
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from .stats import (
    achieved_power,
    required_sample_size,
    two_proportion_ztest,
    welch_ttest,
)

ALPHA = 0.05
POWER_TARGET = 0.80
MDE = 0.03  # minimum detectable (absolute) effect we designed around: 3 pp

HERE = Path(__file__).parent
IMG_DIR = Path("docs/img")


def load_experiment(source: str) -> pd.DataFrame:
    path = Path(source) / "experiment_assignment.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found — run `make generate` first (or pass --source data/raw/sample)."
        )
    return pd.read_parquet(path)


def summarize(df: pd.DataFrame) -> dict:
    g = df.groupby("variant")["engaged_next_day"]
    counts = g.agg(["sum", "count"]).rename(columns={"sum": "engaged", "count": "n"})
    a = counts.loc["A"]
    b = counts.loc["B"]
    return {
        "x_a": int(a["engaged"]), "n_a": int(a["n"]), "p_a": a["engaged"] / a["n"],
        "x_b": int(b["engaged"]), "n_b": int(b["n"]), "p_b": b["engaged"] / b["n"],
        "arr_a": df.loc[df.variant == "A", "engaged_next_day"].to_numpy(),
        "arr_b": df.loc[df.variant == "B", "engaged_next_day"].to_numpy(),
    }


def make_plots(s: dict) -> list[Path]:
    IMG_DIR.mkdir(parents=True, exist_ok=True)
    paths = []

    # 1) engagement rate by variant with Wald 95% error bars
    fig, ax = plt.subplots(figsize=(5, 4))
    rates = [s["p_a"], s["p_b"]]
    errs = [
        1.96 * np.sqrt(p * (1 - p) / n)
        for p, n in [(s["p_a"], s["n_a"]), (s["p_b"], s["n_b"])]
    ]
    ax.bar(["A (control)", "B (treatment)"], rates, yerr=errs, capsize=8,
           color=["#888", "#3b7"])
    ax.set_ylabel("Next-day engagement rate")
    ax.set_title("Engagement by variant (95% CI)")
    for i, r in enumerate(rates):
        ax.text(i, r + 0.005, f"{r:.1%}", ha="center")
    fig.tight_layout()
    p1 = IMG_DIR / "ab_engagement_by_variant.png"
    fig.savefig(p1, dpi=120)
    plt.close(fig)
    paths.append(p1)

    # 2) power curve vs per-group sample size at the designed MDE
    fig, ax = plt.subplots(figsize=(6, 4))
    ns = np.arange(100, 6000, 100)
    powers = [achieved_power(s["p_a"], s["p_a"] + MDE, int(n)) for n in ns]
    ax.plot(ns, powers, color="#3b7")
    ax.axhline(POWER_TARGET, ls="--", color="#c33", label=f"target power {POWER_TARGET}")
    n_req = required_sample_size(s["p_a"], MDE, ALPHA, POWER_TARGET)
    ax.axvline(n_req, ls=":", color="#333", label=f"required n/group ≈ {n_req:,}")
    ax.axvline(s["n_a"], ls=":", color="#3577b7", label=f"actual n/group ≈ {s['n_a']:,}")
    ax.set_xlabel("Sample size per group")
    ax.set_ylabel("Power")
    ax.set_title(f"Power vs n at MDE={MDE:.0%} (p_ctrl={s['p_a']:.1%})")
    ax.legend(fontsize=8)
    fig.tight_layout()
    p2 = IMG_DIR / "ab_power_curve.png"
    fig.savefig(p2, dpi=120)
    plt.close(fig)
    paths.append(p2)
    return paths


def write_results(s: dict, z, t, n_req: int, power_now: float, plots: list[Path]) -> Path:
    diff = s["p_b"] - s["p_a"]
    significant = z.p_value < ALPHA
    out = HERE / "results.md"
    out.write_text(
        f"""# A/B Test Results — notification template A vs B

> Generated by `analysis/ab_test/ab_test.py`. **Synthetic data.**

## Setup

- **Unit:** user. **Variant:** A = control template, B = new template.
- **Outcome:** `engaged_next_day` (binary: opened/acted the next day).
- **Primary test:** two-proportion z-test (binary outcome). Welch t-test reported
  as a cross-check.
- **alpha = {ALPHA}** (two-sided), **target power = {POWER_TARGET}**,
  **designed MDE = {MDE:.0%}** absolute lift.

## Hypotheses

- **H0:** engagement_rate(B) = engagement_rate(A)  (the new template has no effect)
- **H1:** engagement_rate(B) ≠ engagement_rate(A)

## Observed

| Variant | Users (n) | Engaged | Rate |
|---|---:|---:|---:|
| A (control)   | {s['n_a']:,} | {s['x_a']:,} | {s['p_a']:.2%} |
| B (treatment) | {s['n_b']:,} | {s['x_b']:,} | {s['p_b']:.2%} |
| **Difference (B − A)** | | | **{diff:+.2%}** |

## Results

- **{z}**
- **{t}**
- Decision at alpha={ALPHA}: **{"REJECT H0 — significant" if significant else "FAIL TO REJECT H0 — not significant"}**.

The z-test and Welch t-test agree (expected: with a 0/1 outcome and these sample
sizes the two are asymptotically equivalent).

## Sample size & power (this is the important part)

To detect the designed **{MDE:.0%}** absolute lift at alpha={ALPHA},
power={POWER_TARGET}, the normal-approximation formula requires
**≈ {n_req:,} users per group** ({2 * n_req:,} total).

This experiment actually ran with **{s['n_a']:,} per group**, giving an achieved
power of only **≈ {power_now:.0%}** for a {MDE:.0%} effect. So a non-significant
result here is **inconclusive, not evidence of no effect** — the study is
underpowered by design (the synthetic universe has 500 users). With the required
~{n_req:,}/group, the same true effect would be detectable.

See `docs/img/ab_power_curve.png`.

## Threats to validity (what would have invalidated this)

- **Underpowered:** the dominant issue here — too few users to detect a small
  lift, so absence of significance ≠ absence of effect.
- **Peeking / optional stopping:** running the test repeatedly and stopping when
  p<0.05 inflates the false-positive rate. The analysis is run once, post-hoc.
- **Assignment imbalance / SRM:** if the A/B split deviated from 50/50 beyond
  chance (sample-ratio mismatch), randomization is suspect. Here n_A≈n_B.
- **Outcome leakage / contamination:** if a user could see both templates, or the
  "next-day engagement" window overlapped the assignment, the effect would be
  biased. The synthetic design assigns one variant per user.
- **Novelty effect:** a new template can spike engagement transiently; a longer
  horizon than "next day" would test durability.

## Plots

{chr(10).join(f"- ![{p.stem}]( /{p.as_posix()} )" for p in plots)}
""",
        encoding="utf-8",
    )
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Run the notification A/B test.")
    ap.add_argument("--source", default="data/raw", help="dir with experiment_assignment.parquet")
    args = ap.parse_args()

    df = load_experiment(args.source)
    s = summarize(df)

    z = two_proportion_ztest(s["x_a"], s["n_a"], s["x_b"], s["n_b"], ALPHA)
    t = welch_ttest(s["arr_a"], s["arr_b"], ALPHA)
    n_req = required_sample_size(s["p_a"], MDE, ALPHA, POWER_TARGET)
    power_now = achieved_power(s["p_a"], s["p_a"] + MDE, s["n_a"], ALPHA)

    print(z)
    print(t)
    print(f"required n/group for {MDE:.0%} @ power {POWER_TARGET}: {n_req:,}")
    print(f"achieved power at n={s['n_a']:,}/group for a {MDE:.0%} effect: {power_now:.1%}")

    plots = make_plots(s)
    out = write_results(s, z, t, n_req, power_now, plots)
    print(f"wrote {out} and {len(plots)} plots to {IMG_DIR}")


if __name__ == "__main__":
    main()
